In [9]:
import numpy as np
import tensorflow as tf
a = np.arange(1,7)
b = np.arange(1,7)
print(a)
a = a.reshape(2,3)
print(a)
a = a.flatten()
a = np.concatenate([a,a])
print(a)

mad = tf.abs(a - tf.reduce_mean(b)) / len(a)
print(mad)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 1 2 3 4 5 6]
tf.Tensor(
[0.16666667 0.08333333 0.         0.08333333 0.16666667 0.25
 0.16666667 0.08333333 0.         0.08333333 0.16666667 0.25      ], shape=(12,), dtype=float64)
